#   GCP Setup:
#     Artifact Registry repo created:
#       gcloud artifacts repositories create i27academy-devops-dashboard \
#         --repository-format=docker \
#         --location=us-central1 \
#         --project=project-297df0e3-3d6b-40a7-aab

substitutions:
  _REGION: us-central1
  _REPO: i27academy-devops-dashboard
  _IMAGE: i27academy-devops-dashboard
  _SERVICE: i27academy-devops-dashboard
  _PROJECT_ID: 'project-297df0e3-3d6b-40a7-aab'  # Replace with your actual GCP project ID

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${COMMIT_SHA}'

steps:
  # Build the image, tagged with the commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${COMMIT_SHA}'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${COMMIT_SHA}'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--port=8000'
      - '--allow-unauthenticated'
      - '--set-env-vars=SERVER_PORT=8000,SPRING_PROFILES_ACTIVE=cloudrun'



options:
  logging: CLOUD_LOGGING_ONLY