name: Path Filters
on:
    push:
      branches: 
      - master
      paths:
        - 'src/**' # Any file in src folder
        - 'pom.xml' # pom.xml change
        - Dockerfile # docker file changed
jobs: 
    show-information:
        name: Push Trigger info
        runs-on: ubuntu-latest
        steps:
        - name: Show triggered information
          run: |
            echo "======================="
            echo "Details of my workflow"
            echo "Event Name is :       ${{ github.event_name }}"
            echo "Reposiroty Name is:   ${{ github.repository }}"
            echo "Branch  is :          ${{ github.ref_name }}"
            echo "Actor is :            ${{ github.actor }}"
            echo "Commit SHA is:        ${{ github.sha }}"