
name: path filter workflow
on: 
    push:
        branches:
         - main
        paths:
        - 'src/**'
        - 'pom.xml' 
jobs:
    path-filter:    
      runs-on: ubuntu-latest
      steps:
      - name: push trigger info 
        run: echo "this is path filter for push triggers"

