name: run-workflow-1
on: 
    schedule:
        - cron: '*/5 * * * *'
jobs:
    workflow-1:
      runs-on: ubuntu-latest
      steps:
        - name: testing workflow-1
          run: |
            echo "sleeping for 30"            
            sleep 30


# we have custom runners 
# public runners            