name: run-workflow-2
on:
    workflow_run:
      workflows:
      - run-workflow-1  
      types:
        - completed 
jobs:
    workflow-2:
      runs-on: ubuntu-latest
      steps:
        - name: testing workflow
          run: echo " these worklow runs on the after workflow completed"

