name: run-workflow-2
on: 
    workflow_run:
        workflows:
        - run-workflow-1   
        types:
        - completed     
jobs:
    workflow-1:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - name: testing workflow-2
          run: |
            echo "testing workflow 1"

# But if workflow -1 is failed , but workflow -2 also triggered 

#this is situation called some times workflows are failed, but workflow-2 will be triggred.

#In this we use if condition we mentioned explicitly for success


